### ISSUE TITLE
Getting `TypeError: Cannot set property 'fileSystem' of null` when trying to run the app. 

### ISSUE THREAD

**Issue by philippeowagner** [amitmerchant1990/ionic-markdownify#1]
I'm on macOS, all dependencies installed. Any ideas why?

**Comment by amitmerchant1990** [comment]
Hi @philippeowagner 

I've gone through this issue and it seems the issue is related to the ionic app script which is been updated recently. You got to do the following:

Update your ionic app scripts to the latest version. It is 1.0.0 for RC5 release.

Run `npm install @ionic/app-scripts@latest --save-dev`

And then `npm install && ionic serve` and you should be good to go.

Let me know if you still face any issues.

**Comment by philippeowagner** [comment]
Getting 

```
├── UNMET PEER DEPENDENCY sw-toolbox@*
└── UNMET PEER DEPENDENCY typescript@2.0.9
```
, but the app is running. Thanks @amitmerchant1990

**Comment by amitmerchant1990** [comment]
Awesome!
